Added CanMaximize property to Titlebar
lepoco/wpfui pull request #115
Opened 2022-03-26 09:12 UTC by JannesStroehlein

Hello,

I found it very unelegant to just point the MaximizeActionOverride to an empty action. Like this:
```csharp
private void MaximizeOverwrite(TitleBar tb, Window w) 
{

}
```
So I added a property to the Titlebar class that completely disables maximizing (for me just disabling the maximize button wasn't sufficient, because double clicking still maximized the Window).

I hope this addition is in line with your design principles.

With kind regards

Jannes

PS: I also thought about automatically disabling minimize, maximize, resize and snapping when the WindowStyle is set to ToolWindow.

2022-03-27 18:47 UTC, pomianowski requested changes

2022-03-27 18:47 UTC, pomianowski commented on WPFUI/Controls/TitleBar.cs
> +            typeof(bool), typeof(TitleBar), new PropertyMetadata(false));
It should be `true` by default

2022-03-27 19:49 UTC, JannesStroehlein commented on WPFUI/Controls/TitleBar.cs
> +            typeof(bool), typeof(TitleBar), new PropertyMetadata(false));
Done

2022-03-29 10:12 UTC, pomianowski approved these changes

2022-03-29 10:30 UTC, merged