Feature/gridview-min-max-widths
lepoco/wpfui pull request #982
Opened 2024-03-01 01:28 UTC by koal44

Add `MinWidth` and `MaxWidth` support for `GridView`
## Pull request type

- [x] Feature

## Info

This feature is a branch off of PR #979. It adds min/max width support for `GridView`. It uses a fair bit of reflection to maintain support for dragging column headers.

- Extends `GridViewColumn` to have dependency properties `MaxWidth` and `MinWidth`
- Overrides `ArrangeOverride()` on `GridViewHeaderRowPresenter` (header row) and `GridViewRowPresenter` (data rows)
- Update `ListView` and `ListViewItem` to use the extended classes
- Update the GalleryApp to showcase min/max widths

2024-03-19 13:37 UTC, pomianowski requested changes

2024-03-19 13:37 UTC, pomianowski commented on src/Wpf.Ui/Controls/ListView/GridViewColumn.cs
> +public class GridViewColumn : System.Windows.Controls.GridViewColumn
Is the **Controls/ListView** directory the right place for these classes? Maybe **Controls/GridView** would be more appropriate

2024-03-19 13:37 UTC, pomianowski commented on src/Wpf.Ui/Controls/ListView/GridViewColumn.cs
> +    protected virtual void OnMinWidthChanged(DependencyPropertyChangedEventArgs e)
Missing docs for public api

2024-03-19 13:37 UTC, pomianowski commented on src/Wpf.Ui/Controls/ListView/ListView.cs
> +public class ListView : System.Windows.Controls.ListView
Missing docs for public control

2024-03-19 13:37 UTC, pomianowski commented on src/Wpf.Ui/Controls/ListView/GridViewRowPresenter.cs
> +public class GridViewRowPresenter : System.Windows.Controls.GridViewRowPresenter
Missing docs for public control

2024-03-19 13:37 UTC, pomianowski commented on src/Wpf.Ui/Controls/ListView/GridViewHeaderRowPresenter.cs
> +public class GridViewHeaderRowPresenter : System.Windows.Controls.GridViewHeaderRowPresenter
Missing docs for public control

2024-03-20 03:16 UTC, koal44 commented
I've added documentation and separated `GridView` related components into a Controls/GridView folder.

The `ArrangeOverride()` methods on RowPresenter classes was simplified and there's only one reflected field now. Additionally XAML styling is only on Wpf.Ui custom controls, so this library won't interfere with how vanilla `ListView` operates. Instead, to use the Wpf.Ui library's `ListView` styles, one would need to use all the ui custom classes.

TODO: restyle `GridViewColumnHeader.xaml` to support column resizing (logic should already be baked into the control).

2024-03-22 15:13 UTC, pomianowski approved these changes

2024-03-24 18:21 UTC, koal44 commented
Added drag resizing support.

![gridview-resizing](https://github.com/lepoco/wpfui/assets/78566945/70b3c6c5-8bbd-4f2c-994e-aa0b9464128c)

2024-03-24 20:12 UTC, pomianowski approved these changes

2024-03-24 20:12 UTC, merged